name    'ncsudrmcclus-vclmgmt'
version '0.0.1'
source 'UNKNOWN'
author 'ncsudrmcclus'
license 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs-stdlib', '>= 4.1.0'
dependency 'pdxmph/subversion', '>= 1.0.1'
dependency 'razorsedge/network', '>= 2.3.0'
dependency 'camptocamp/dhcp', '>= 0.3.0'
dependency 'camptocamp/bind', '>= 0.2.2'
dependency 'puppetlabs/mysql','>= 2.2.3'
