name    'oeudtinsanmie-vclmgmt'
version '0.1.0'
source 'https://github.ncsu.edu/engr-csc-netlabs/puppetmodules.git'
author 'Douglas McClusky'
license 'Apache License, Version 2.0'
summary 'Install VCL and manage its database and xCAT resources.  Currently supports computers, networks and base images.'
description 'Install VCL and manage its database and xCAT resources.  Currently supports computers, networks and base images.'
project_page 'https://github.ncsu.edu/engr-csc-netlabs/puppetmodules/vclmgmt'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'oeudtinsanmie/xcat', '>=0.1.0'
dependency 'razorsedge/network', '>= 3.0.0'
dependency 'puppetlabs/mysql','>= 2.2.3'
dependency 'puppetlabs/vcsrepo', '>=1.0.1'
dependency 'puppetlabs/firewall', '>=1.0.2'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'gini/archive', '>=0.2.0'
dependency 'camptocamp/openssl', '>=0.3.2'
